name: Pull
on:
  schedule:
    - cron:  '*/10 * * * *'
env:
  KBC_STORAGE_API_TOKEN: ${{ secrets.KBC_STORAGE_API_TOKEN }}
jobs:
  kbc_pull:
    # Automatic pull can be canceled by push
    concurrency:
     group: main_branch
     cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install Keboola as Code CLI
        uses: ./.github/actions/install
      - name: Pull from Keboola Connection
        id: kbc_pull_step
        run: |
          kbc pull --force
      # Automatic pull can be canceled by push, wait a while
      - name: Wait
        run: sleep 20
      - name: Commit and push
        run: |
          currentDate=`date +%s`
          git config --global user.name 'Keboola CLI'
          git config --global user.email 'keboola-cli@users.noreply.github.com'
          git add -A
          git commit -am "Automatic pull $currentDate\n\n$pull_stdout" || true
          git push
        env:
          pull_stdout: ${{join(steps.kbc_pull_step.outputs.*, '\n')}}
