name: Push
on:
  push:
    branches:    
      - 'main'
      - 'master'
env:
  KBC_STORAGE_API_TOKEN: ${{ secrets.KBC_STORAGE_API_TOKEN }}
  COMMIT_REF: ${{ github.sha }}
  COMMIT_MSG: ${{ github.event.head_commit.message }}
jobs:
  kbc-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install Keboola as Code CLI
        uses: ./.github/actions/install
      - name: Push to Keboola Connection
        run: |
          kbc push "#KeboolaCLI: commit $COMMIT_REF"